### ISSUE TITLE
Disabling furigana for known words

### ISSUE THREAD

**Issue by Helmasko** [max-kamps/jpdb-browser-reader#28]
Would be great if there was an option to disable furigana for known words.
An option for disabling it for all words would also be a nice addition to that.

**Comment by Helmasko** [comment]
I just noticed in the Readme it mentioned the CSS, which I tried and it didn't work correctly. Adding .jpdb-word.never-forget .jpdb-furi fixed it for me. It might be worth updating the code on the Readme.

**Comment by max-kamps** [comment]
I've improved the CSS examples in the readme a bit, hopefully that should help :)
As for a nicer option for customization that does not involve CSS, that is planned! Rather low priority, though.
