### ISSUE TITLE
Switch build script from shell commands to JavaScript

### ISSUE THREAD

**Issue by max-kamps** [max-kamps/jpdb-browser-reader#9]
Using shell features for the build script is extremely brittle and non-portable. I am only able to test the code on Linux, and do not want to accidentally break it for Windows users.

Porting the current build commands in `package.json` to a JavaScript build script instead would be much appreciated.

**Comment by nico-abram** [comment]
As an example, it seems on windows the build script is currently broken because `copy-and-watch --watch 'src/**/!(*.{mts,ts,tsx})'` is trying to read from a folder called `'src`, and I think the quotes are needed to avoid shell expansion in bash
